### ISSUE TITLE
Add Event to Published Schedule (Full Flow)

### ISSUE THREAD

**Issue by SubinQKim** [ctc-uci/aiss-frontend#34]
## NOTE
This task carries over from the previous sprint. However, it will now be reduced to a 1 pair task.

## Instructions
- In the past few sprints, we’ve worked on a few components related to adding an event to the Published Schedule, including a form to add events to the Published Schedule and a “Day Planner” component which allows users to visualize events for a given day.
- In this task, we’ll be tying everything together to allow the user to add an event to the Published Schedule from start to finish.
- Reference the flow listed in the Acceptance Criteria to determine what to add and pull together
- Related to backend tasks [#46](https://github.com/ctc-uci/aiss-backend/issues/46)

## Notes
- For specific flows and design questions, please work with Elise from the design team
- Most of the components you need to complete this task are already made, so you just need to put them together. If you have any questions about how these components work, you can ask the pairs that made them
  - Calendar View (Sean + Alyssia)
  - Catalog Table Search + Filter (Philip + Subin)
  - Publish Schedule Form (Chloe + Lana)
- Currently, the Search/Filter functionality is inside of the Catalog page. For this task, please move it to a separate component so that it can be reused in both the Catalog page and the Day Planner

## Acceptance Criteria
- On main published schedule page, create add button which opens up a modal to add a new day to the published schedule
- Adding a new day to the published schedule renders the Planner Layout component in a fullscreen modal
Within Planner Layout modal:
    - User should be able to use the search bar and dropdowns to filter events (filter and query catalog component does this already)
    - User can add events in catalog and/or new events not already in the catalog to Published Schedule through create new event form (component linked in Resources)
    - User can modify existing events in catalog by clicking on the event in the table, bringing up an editable pre-populated form (same component as above)
    - Submission of the create new event form keeps user in Planner Layout modal
    - Clicking the cancel button (bottom right) closes the modal

## Resources
- [filter and query catalog - Frontend](https://github.com/ctc-uci/aiss-frontend/pull/31)
- [filter and query catalog - Backend](https://github.com/ctc-uci/aiss-backend/pull/43)
- [create new event form - Frontend](https://github.com/ctc-uci/aiss-frontend/blob/dev/src/components/CreateEventForm/CreateEventForm.jsx#L36)
- [day planner figma](https://www.figma.com/file/CmrgQbRKVLJWVhSzXxAdad/Low-High-Fidelity?type=design&node-id=761-4535&mode=design&t=P5LePFJFnpj9GTpL-0)

**Comment by ThatMegamind** [comment]
## New Instructions
- In the last sprint, the modals have been set up for the published schedule to add new events or edit them. However the actual functionality of adding/editing events to the published schedule has not been implemented yet. 
- For this task you will need to finish adding events to the published schedule and enable users to modify existing events in the catalog.

## Notes
- There is preexisting hover functionality of the table rows that you can use for the edit events done by Kade and Lianne.
- The main difference between what they did, is that it opens a form specific for the catalog events.. In this sprint the hover functionality of the catalog while in the day planner modal needs to open a pre-populated form (same component as the “new add event” form).

## Acceptance Criteria
- Check that the events are added to both the published schedule and catalog (for both new events using the add button and events pre-existing from the catalog)
Within Planner Layout modal:
    - Submission of the create new event form keeps user in Planner Layout modal
