### ISSUE TITLE
Complete Notification Page Functionality (Frontend)

### ISSUE THREAD

**Issue by h0ethan04** [ctc-uci/aiss-frontend#36]
## Instructions
The individual notification component has been completed, now it's time to assemble the entire window.
There are two things displayed in the notifications center: pending accounts and events recently added to the Published Schedule. This task has an associated backend task ([see #45 on backend](https://github.com/ctc-uci/aiss-backend/issues/45#issue-2116764795)). For the frontend, this task requires the following:
- Admin users should be able to see pending user accounts and recently created Published Schedule events
- Notification window should group pending user accounts by date of creation
- Display Published Schedule events created in the last week
- Display Published Schedule events marked as confirmed in the last week

## Notes
- If you have any questions about designs talk to Selina

## Acceptance Criteria
- Notifications are now displayed by day
- Approving an account adds a notification indicating the user was approved
- Newly confirmed events in the Published Schedule show up as notifications
- Adding events to the published schedule result in a notification

## Resources
[Notifications Center Figma](https://www.figma.com/file/CmrgQbRKVLJWVhSzXxAdad/Low-High-Fidelity?type=design&node-id=229-4159&mode=design&t=Pcy0bzBRjhwEmFQ7-4)
[Notifications Page Component](https://github.com/ctc-uci/aiss-frontend/blob/dev/src/pages/Notifications/Notifications.jsx)
[Chakra-UI docs](https://chakra-ui.com/docs/components)

**Comment by seancfong** [comment]
> Notification window should group pending user accounts by date of creation.

@h0ethan04 The `users` table currently doesn't have a creation date column. Do you know when the schema will be updated for this task?

**Comment by h0ethan04** [comment]
That's currently part of the backend task, the column name is `approved_on`. I think we had decided that when a new user is created the `approved_on` column would initially store the creation date then get overwritten once the account is approved. @seancfong
