### ISSUE TITLE
Student View Cleanup

### ISSUE THREAD

**Issue by ThatMegamind** [ctc-uci/aiss-frontend#67]
## Instructions
- Currently, the Student view of the website allows the user to confirm tentative events, edit events, delete events, and delete days on the Published Schedule. The dropdown for seasons also appears, although it's diabled
- The goal of this task is to completely remove and hide all of this functionality from Student accounts

## Notes
N/A

## Acceptance Criteria
- Student users cannot confirm tentative events, edit events, delete events, or delete days from the Published Schedule, nor can they see the option to do so
- Student users cannot see the dropdown for seasons

## Resources
- [Student High Fidelity Design](https://www.figma.com/file/CmrgQbRKVLJWVhSzXxAdad/Low-High-Fidelity?type=design&node-id=1099-7292&mode=design&t=69dOB2HFhdZLuD8q-4)

**Comment by ethan-so** [comment]
got assigned by accident LOL - graduated last year and only did CTC the year before that. good luck to yall though :)

**Comment by h0ethan04** [comment]
Oops LMAO sorry about that, thanks for fixing this :)
